/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPatientUploadMriRouteImport } from './routes/_authenticated/patient/upload-mri'
import { Route as AuthenticatedPatientSupportRouteImport } from './routes/_authenticated/patient/support'
import { Route as AuthenticatedPatientProfileRouteImport } from './routes/_authenticated/patient/profile'
import { Route as AuthenticatedPatientMriHistoryRouteImport } from './routes/_authenticated/patient/mri-history'
import { Route as AuthenticatedPatientDashboardRouteImport } from './routes/_authenticated/patient/dashboard'
import { Route as AuthenticatedPatientChatbotRouteImport } from './routes/_authenticated/patient/chatbot'
import { Route as AuthenticatedDoctorSupportRouteImport } from './routes/_authenticated/doctor/support'
import { Route as AuthenticatedDoctorReviewedAnalysesRouteImport } from './routes/_authenticated/doctor/reviewed-analyses'
import { Route as AuthenticatedDoctorProfileRouteImport } from './routes/_authenticated/doctor/profile'
import { Route as AuthenticatedDoctorPendingMriRouteImport } from './routes/_authenticated/doctor/pending-mri'
import { Route as AuthenticatedDoctorPatientsRouteImport } from './routes/_authenticated/doctor/patients'
import { Route as AuthenticatedDoctorDashboardRouteImport } from './routes/_authenticated/doctor/dashboard'
import { Route as AuthenticatedAdminSupportRouteImport } from './routes/_authenticated/admin/support'
import { Route as AuthenticatedAdminPatientsRouteImport } from './routes/_authenticated/admin/patients'
import { Route as AuthenticatedAdminNotificationsRouteImport } from './routes/_authenticated/admin/notifications'
import { Route as AuthenticatedAdminDoctorsRouteImport } from './routes/_authenticated/admin/doctors'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin/dashboard'
import { Route as AuthenticatedAdminAssignDoctorRouteImport } from './routes/_authenticated/admin/assign-doctor'
import { Route as AuthenticatedPatientMriIdRouteImport } from './routes/_authenticated/patient/mri.$id'
import { Route as AuthenticatedDoctorMriIdReviewRouteImport } from './routes/_authenticated/doctor/mri.$id.review'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPatientUploadMriRoute =
  AuthenticatedPatientUploadMriRouteImport.update({
    id: '/patient/upload-mri',
    path: '/patient/upload-mri',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPatientSupportRoute =
  AuthenticatedPatientSupportRouteImport.update({
    id: '/patient/support',
    path: '/patient/support',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPatientProfileRoute =
  AuthenticatedPatientProfileRouteImport.update({
    id: '/patient/profile',
    path: '/patient/profile',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPatientMriHistoryRoute =
  AuthenticatedPatientMriHistoryRouteImport.update({
    id: '/patient/mri-history',
    path: '/patient/mri-history',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPatientDashboardRoute =
  AuthenticatedPatientDashboardRouteImport.update({
    id: '/patient/dashboard',
    path: '/patient/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPatientChatbotRoute =
  AuthenticatedPatientChatbotRouteImport.update({
    id: '/patient/chatbot',
    path: '/patient/chatbot',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDoctorSupportRoute =
  AuthenticatedDoctorSupportRouteImport.update({
    id: '/doctor/support',
    path: '/doctor/support',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDoctorReviewedAnalysesRoute =
  AuthenticatedDoctorReviewedAnalysesRouteImport.update({
    id: '/doctor/reviewed-analyses',
    path: '/doctor/reviewed-analyses',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDoctorProfileRoute =
  AuthenticatedDoctorProfileRouteImport.update({
    id: '/doctor/profile',
    path: '/doctor/profile',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDoctorPendingMriRoute =
  AuthenticatedDoctorPendingMriRouteImport.update({
    id: '/doctor/pending-mri',
    path: '/doctor/pending-mri',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDoctorPatientsRoute =
  AuthenticatedDoctorPatientsRouteImport.update({
    id: '/doctor/patients',
    path: '/doctor/patients',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDoctorDashboardRoute =
  AuthenticatedDoctorDashboardRouteImport.update({
    id: '/doctor/dashboard',
    path: '/doctor/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminSupportRoute =
  AuthenticatedAdminSupportRouteImport.update({
    id: '/admin/support',
    path: '/admin/support',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminPatientsRoute =
  AuthenticatedAdminPatientsRouteImport.update({
    id: '/admin/patients',
    path: '/admin/patients',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminNotificationsRoute =
  AuthenticatedAdminNotificationsRouteImport.update({
    id: '/admin/notifications',
    path: '/admin/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminDoctorsRoute =
  AuthenticatedAdminDoctorsRouteImport.update({
    id: '/admin/doctors',
    path: '/admin/doctors',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/admin/dashboard',
    path: '/admin/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminAssignDoctorRoute =
  AuthenticatedAdminAssignDoctorRouteImport.update({
    id: '/admin/assign-doctor',
    path: '/admin/assign-doctor',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPatientMriIdRoute =
  AuthenticatedPatientMriIdRouteImport.update({
    id: '/patient/mri/$id',
    path: '/patient/mri/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDoctorMriIdReviewRoute =
  AuthenticatedDoctorMriIdReviewRouteImport.update({
    id: '/doctor/mri/$id/review',
    path: '/doctor/mri/$id/review',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/assign-doctor': typeof AuthenticatedAdminAssignDoctorRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/doctors': typeof AuthenticatedAdminDoctorsRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/patients': typeof AuthenticatedAdminPatientsRoute
  '/admin/support': typeof AuthenticatedAdminSupportRoute
  '/doctor/dashboard': typeof AuthenticatedDoctorDashboardRoute
  '/doctor/patients': typeof AuthenticatedDoctorPatientsRoute
  '/doctor/pending-mri': typeof AuthenticatedDoctorPendingMriRoute
  '/doctor/profile': typeof AuthenticatedDoctorProfileRoute
  '/doctor/reviewed-analyses': typeof AuthenticatedDoctorReviewedAnalysesRoute
  '/doctor/support': typeof AuthenticatedDoctorSupportRoute
  '/patient/chatbot': typeof AuthenticatedPatientChatbotRoute
  '/patient/dashboard': typeof AuthenticatedPatientDashboardRoute
  '/patient/mri-history': typeof AuthenticatedPatientMriHistoryRoute
  '/patient/profile': typeof AuthenticatedPatientProfileRoute
  '/patient/support': typeof AuthenticatedPatientSupportRoute
  '/patient/upload-mri': typeof AuthenticatedPatientUploadMriRoute
  '/patient/mri/$id': typeof AuthenticatedPatientMriIdRoute
  '/doctor/mri/$id/review': typeof AuthenticatedDoctorMriIdReviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/assign-doctor': typeof AuthenticatedAdminAssignDoctorRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/doctors': typeof AuthenticatedAdminDoctorsRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/patients': typeof AuthenticatedAdminPatientsRoute
  '/admin/support': typeof AuthenticatedAdminSupportRoute
  '/doctor/dashboard': typeof AuthenticatedDoctorDashboardRoute
  '/doctor/patients': typeof AuthenticatedDoctorPatientsRoute
  '/doctor/pending-mri': typeof AuthenticatedDoctorPendingMriRoute
  '/doctor/profile': typeof AuthenticatedDoctorProfileRoute
  '/doctor/reviewed-analyses': typeof AuthenticatedDoctorReviewedAnalysesRoute
  '/doctor/support': typeof AuthenticatedDoctorSupportRoute
  '/patient/chatbot': typeof AuthenticatedPatientChatbotRoute
  '/patient/dashboard': typeof AuthenticatedPatientDashboardRoute
  '/patient/mri-history': typeof AuthenticatedPatientMriHistoryRoute
  '/patient/profile': typeof AuthenticatedPatientProfileRoute
  '/patient/support': typeof AuthenticatedPatientSupportRoute
  '/patient/upload-mri': typeof AuthenticatedPatientUploadMriRoute
  '/patient/mri/$id': typeof AuthenticatedPatientMriIdRoute
  '/doctor/mri/$id/review': typeof AuthenticatedDoctorMriIdReviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/admin/assign-doctor': typeof AuthenticatedAdminAssignDoctorRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/doctors': typeof AuthenticatedAdminDoctorsRoute
  '/_authenticated/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/_authenticated/admin/patients': typeof AuthenticatedAdminPatientsRoute
  '/_authenticated/admin/support': typeof AuthenticatedAdminSupportRoute
  '/_authenticated/doctor/dashboard': typeof AuthenticatedDoctorDashboardRoute
  '/_authenticated/doctor/patients': typeof AuthenticatedDoctorPatientsRoute
  '/_authenticated/doctor/pending-mri': typeof AuthenticatedDoctorPendingMriRoute
  '/_authenticated/doctor/profile': typeof AuthenticatedDoctorProfileRoute
  '/_authenticated/doctor/reviewed-analyses': typeof AuthenticatedDoctorReviewedAnalysesRoute
  '/_authenticated/doctor/support': typeof AuthenticatedDoctorSupportRoute
  '/_authenticated/patient/chatbot': typeof AuthenticatedPatientChatbotRoute
  '/_authenticated/patient/dashboard': typeof AuthenticatedPatientDashboardRoute
  '/_authenticated/patient/mri-history': typeof AuthenticatedPatientMriHistoryRoute
  '/_authenticated/patient/profile': typeof AuthenticatedPatientProfileRoute
  '/_authenticated/patient/support': typeof AuthenticatedPatientSupportRoute
  '/_authenticated/patient/upload-mri': typeof AuthenticatedPatientUploadMriRoute
  '/_authenticated/patient/mri/$id': typeof AuthenticatedPatientMriIdRoute
  '/_authenticated/doctor/mri/$id/review': typeof AuthenticatedDoctorMriIdReviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/admin/assign-doctor'
    | '/admin/dashboard'
    | '/admin/doctors'
    | '/admin/notifications'
    | '/admin/patients'
    | '/admin/support'
    | '/doctor/dashboard'
    | '/doctor/patients'
    | '/doctor/pending-mri'
    | '/doctor/profile'
    | '/doctor/reviewed-analyses'
    | '/doctor/support'
    | '/patient/chatbot'
    | '/patient/dashboard'
    | '/patient/mri-history'
    | '/patient/profile'
    | '/patient/support'
    | '/patient/upload-mri'
    | '/patient/mri/$id'
    | '/doctor/mri/$id/review'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/admin/assign-doctor'
    | '/admin/dashboard'
    | '/admin/doctors'
    | '/admin/notifications'
    | '/admin/patients'
    | '/admin/support'
    | '/doctor/dashboard'
    | '/doctor/patients'
    | '/doctor/pending-mri'
    | '/doctor/profile'
    | '/doctor/reviewed-analyses'
    | '/doctor/support'
    | '/patient/chatbot'
    | '/patient/dashboard'
    | '/patient/mri-history'
    | '/patient/profile'
    | '/patient/support'
    | '/patient/upload-mri'
    | '/patient/mri/$id'
    | '/doctor/mri/$id/review'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/admin/assign-doctor'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/doctors'
    | '/_authenticated/admin/notifications'
    | '/_authenticated/admin/patients'
    | '/_authenticated/admin/support'
    | '/_authenticated/doctor/dashboard'
    | '/_authenticated/doctor/patients'
    | '/_authenticated/doctor/pending-mri'
    | '/_authenticated/doctor/profile'
    | '/_authenticated/doctor/reviewed-analyses'
    | '/_authenticated/doctor/support'
    | '/_authenticated/patient/chatbot'
    | '/_authenticated/patient/dashboard'
    | '/_authenticated/patient/mri-history'
    | '/_authenticated/patient/profile'
    | '/_authenticated/patient/support'
    | '/_authenticated/patient/upload-mri'
    | '/_authenticated/patient/mri/$id'
    | '/_authenticated/doctor/mri/$id/review'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/patient/upload-mri': {
      id: '/_authenticated/patient/upload-mri'
      path: '/patient/upload-mri'
      fullPath: '/patient/upload-mri'
      preLoaderRoute: typeof AuthenticatedPatientUploadMriRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/patient/support': {
      id: '/_authenticated/patient/support'
      path: '/patient/support'
      fullPath: '/patient/support'
      preLoaderRoute: typeof AuthenticatedPatientSupportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/patient/profile': {
      id: '/_authenticated/patient/profile'
      path: '/patient/profile'
      fullPath: '/patient/profile'
      preLoaderRoute: typeof AuthenticatedPatientProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/patient/mri-history': {
      id: '/_authenticated/patient/mri-history'
      path: '/patient/mri-history'
      fullPath: '/patient/mri-history'
      preLoaderRoute: typeof AuthenticatedPatientMriHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/patient/dashboard': {
      id: '/_authenticated/patient/dashboard'
      path: '/patient/dashboard'
      fullPath: '/patient/dashboard'
      preLoaderRoute: typeof AuthenticatedPatientDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/patient/chatbot': {
      id: '/_authenticated/patient/chatbot'
      path: '/patient/chatbot'
      fullPath: '/patient/chatbot'
      preLoaderRoute: typeof AuthenticatedPatientChatbotRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/doctor/support': {
      id: '/_authenticated/doctor/support'
      path: '/doctor/support'
      fullPath: '/doctor/support'
      preLoaderRoute: typeof AuthenticatedDoctorSupportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/doctor/reviewed-analyses': {
      id: '/_authenticated/doctor/reviewed-analyses'
      path: '/doctor/reviewed-analyses'
      fullPath: '/doctor/reviewed-analyses'
      preLoaderRoute: typeof AuthenticatedDoctorReviewedAnalysesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/doctor/profile': {
      id: '/_authenticated/doctor/profile'
      path: '/doctor/profile'
      fullPath: '/doctor/profile'
      preLoaderRoute: typeof AuthenticatedDoctorProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/doctor/pending-mri': {
      id: '/_authenticated/doctor/pending-mri'
      path: '/doctor/pending-mri'
      fullPath: '/doctor/pending-mri'
      preLoaderRoute: typeof AuthenticatedDoctorPendingMriRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/doctor/patients': {
      id: '/_authenticated/doctor/patients'
      path: '/doctor/patients'
      fullPath: '/doctor/patients'
      preLoaderRoute: typeof AuthenticatedDoctorPatientsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/doctor/dashboard': {
      id: '/_authenticated/doctor/dashboard'
      path: '/doctor/dashboard'
      fullPath: '/doctor/dashboard'
      preLoaderRoute: typeof AuthenticatedDoctorDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/support': {
      id: '/_authenticated/admin/support'
      path: '/admin/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AuthenticatedAdminSupportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/patients': {
      id: '/_authenticated/admin/patients'
      path: '/admin/patients'
      fullPath: '/admin/patients'
      preLoaderRoute: typeof AuthenticatedAdminPatientsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/notifications': {
      id: '/_authenticated/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AuthenticatedAdminNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/doctors': {
      id: '/_authenticated/admin/doctors'
      path: '/admin/doctors'
      fullPath: '/admin/doctors'
      preLoaderRoute: typeof AuthenticatedAdminDoctorsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/assign-doctor': {
      id: '/_authenticated/admin/assign-doctor'
      path: '/admin/assign-doctor'
      fullPath: '/admin/assign-doctor'
      preLoaderRoute: typeof AuthenticatedAdminAssignDoctorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/patient/mri/$id': {
      id: '/_authenticated/patient/mri/$id'
      path: '/patient/mri/$id'
      fullPath: '/patient/mri/$id'
      preLoaderRoute: typeof AuthenticatedPatientMriIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/doctor/mri/$id/review': {
      id: '/_authenticated/doctor/mri/$id/review'
      path: '/doctor/mri/$id/review'
      fullPath: '/doctor/mri/$id/review'
      preLoaderRoute: typeof AuthenticatedDoctorMriIdReviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminAssignDoctorRoute: typeof AuthenticatedAdminAssignDoctorRoute
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminDoctorsRoute: typeof AuthenticatedAdminDoctorsRoute
  AuthenticatedAdminNotificationsRoute: typeof AuthenticatedAdminNotificationsRoute
  AuthenticatedAdminPatientsRoute: typeof AuthenticatedAdminPatientsRoute
  AuthenticatedAdminSupportRoute: typeof AuthenticatedAdminSupportRoute
  AuthenticatedDoctorDashboardRoute: typeof AuthenticatedDoctorDashboardRoute
  AuthenticatedDoctorPatientsRoute: typeof AuthenticatedDoctorPatientsRoute
  AuthenticatedDoctorPendingMriRoute: typeof AuthenticatedDoctorPendingMriRoute
  AuthenticatedDoctorProfileRoute: typeof AuthenticatedDoctorProfileRoute
  AuthenticatedDoctorReviewedAnalysesRoute: typeof AuthenticatedDoctorReviewedAnalysesRoute
  AuthenticatedDoctorSupportRoute: typeof AuthenticatedDoctorSupportRoute
  AuthenticatedPatientChatbotRoute: typeof AuthenticatedPatientChatbotRoute
  AuthenticatedPatientDashboardRoute: typeof AuthenticatedPatientDashboardRoute
  AuthenticatedPatientMriHistoryRoute: typeof AuthenticatedPatientMriHistoryRoute
  AuthenticatedPatientProfileRoute: typeof AuthenticatedPatientProfileRoute
  AuthenticatedPatientSupportRoute: typeof AuthenticatedPatientSupportRoute
  AuthenticatedPatientUploadMriRoute: typeof AuthenticatedPatientUploadMriRoute
  AuthenticatedPatientMriIdRoute: typeof AuthenticatedPatientMriIdRoute
  AuthenticatedDoctorMriIdReviewRoute: typeof AuthenticatedDoctorMriIdReviewRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminAssignDoctorRoute: AuthenticatedAdminAssignDoctorRoute,
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedAdminDoctorsRoute: AuthenticatedAdminDoctorsRoute,
  AuthenticatedAdminNotificationsRoute: AuthenticatedAdminNotificationsRoute,
  AuthenticatedAdminPatientsRoute: AuthenticatedAdminPatientsRoute,
  AuthenticatedAdminSupportRoute: AuthenticatedAdminSupportRoute,
  AuthenticatedDoctorDashboardRoute: AuthenticatedDoctorDashboardRoute,
  AuthenticatedDoctorPatientsRoute: AuthenticatedDoctorPatientsRoute,
  AuthenticatedDoctorPendingMriRoute: AuthenticatedDoctorPendingMriRoute,
  AuthenticatedDoctorProfileRoute: AuthenticatedDoctorProfileRoute,
  AuthenticatedDoctorReviewedAnalysesRoute:
    AuthenticatedDoctorReviewedAnalysesRoute,
  AuthenticatedDoctorSupportRoute: AuthenticatedDoctorSupportRoute,
  AuthenticatedPatientChatbotRoute: AuthenticatedPatientChatbotRoute,
  AuthenticatedPatientDashboardRoute: AuthenticatedPatientDashboardRoute,
  AuthenticatedPatientMriHistoryRoute: AuthenticatedPatientMriHistoryRoute,
  AuthenticatedPatientProfileRoute: AuthenticatedPatientProfileRoute,
  AuthenticatedPatientSupportRoute: AuthenticatedPatientSupportRoute,
  AuthenticatedPatientUploadMriRoute: AuthenticatedPatientUploadMriRoute,
  AuthenticatedPatientMriIdRoute: AuthenticatedPatientMriIdRoute,
  AuthenticatedDoctorMriIdReviewRoute: AuthenticatedDoctorMriIdReviewRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
